### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by PerfectSlayer** [PerfectSlayer/fosfox#2]
List of remaining tasks before public release:
- [x] Implement location strategy
- [x] Implement default location preferences setting
- [x] Cypher API token
- [x] Open downloader application on action button
